name = "moe-counter-cf"
type = "javascript"
account_id = "80725acb026151ff25ee051ed37d13a0"
zone_id = "5d676d5e89ee0ea4a3799182196da5d2"
workers_dev = false
route = "counter.shirakii.com/*"
compatibility_date = "2022-03-12"
kv_namespaces = [
  { binding = "KV", id = "109c0ba9a9f545539e80efefaf413e94" },
]

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
